sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t alcik98/fibonacci2 -f Dockerfile.dev1 .

script:
  - docker run -e CI=true alcik98/fibonacci2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "fibonacci"
  env: "fibonacci-env"
  bucket_name: "elasticbeanstalk-us-east-2-219628312044"
  bucket_path: "fibonacci"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
